name: Chrome Extension Build

on:
  push:
    branches:
      - main  # Oder welcher Branch auch immer du verwenden möchtest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
#    steps:
#    - uses: actions/checkout@v4

#    - name: Pack Extension
#      run: chrome --pack-extension=./src

#    - name: Upload Artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: extension-crx
#        path: every-smart.crx
