name: Chrome Extension Build

on:
  push:
    branches:
      - main  # Oder welcher Branch auch immer du verwenden möchtest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - uses: actions/checkout@v4
  
      - name: Pack Extension
        run: chrome --pack-extension=./src && mv src.crx every-smart.crx && mv src.pem every-smart.pem

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: every-smart-crx
          path: |
            every-smart.crx
            every-smart.pem
      - name: Release erstellen
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Dies ist ein automatisiertes Release des Build-Artefakts.
          draft: false
          prerelease: false
          asset_path: every-smart.crx
          asset_name: every-smart.crx
          asset_content_type: application/x-chrome-extension
